Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 20

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/Documentation:
  Enabled: false

Naming/PredicateName:
  Exclude:
    - app/serializers/**/*

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - id

Naming/UncommunicativeBlockParamName:
  AllowedNames:
    - id

Metrics/BlockLength:
  Exclude:
    - config/routes.rb
  Enabled: false
